spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.10.20:3306/NEW_MEC_CORE?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: NEW_MEC_CORE
      password: new_mec_core
      driver-class-name: com.mysql.jdbc.Driver